---
- hosts: zabbix
  become: yes
  tasks:
  - name: "Check Old Version"
    command: zabbix_agentd -V
    register: old
  - name: "Result"
    debug:
      msg: "{{old}}"
  - name: "Update Repo Zabbix" 
    when: '"6.0." not in old.stdout'
    replace:
      path: /etc/yum.repos.d/zabbix.repo
      regexp: '\d.\d'
      replace: '6.0'
  - name: "Update ZAbbix Agent"
    when: '"6.0." not in old.stdout'
    ansible.builtin.yum:
      name: zabbix-agent
      enablerepo: zabbix
      state: latest
  - name: "Check New Version"
    command: zabbix_agentd -V
    register: new
  - name: "Result"
    debug:
      msg: "{{new}}"
