---
- hosts: zabbix
  become: no
  gather_facts: no
  tasks:
  - name: "Check Old Version"
    command: zabbix_agentd -V
    register: old
  - name: "Result"
    debug:
      msg: "{{old}}"
  - name: "Update Repo Zabbix" 
    when: '"6.0." not in old'
    replace:
      path: /etc/yum.repos.d/zabbix.repo
      regexp: 'baseurl=http://repo.zabbix.com/zabbix/5.0/rhel/8/$basearch/'
      replace: 'baseurl=http://repo.zabbix.com/zabbix/6.0/rhel/8/$basearch/'
  - name: "Update ZAbbix Agent"
    when: '"6.0." not in old'
    ansible.builtin.yum:
      name: zabbix-agent
      enablerepo: zabbix
      state: present
